apiVersion: v1
kind: Service
metadata:
  name: phoenix-service
spec:
  type: NodePort
  selector:
    app: phoenix
  ports:
    - name: ui
      port: 6006
      targetPort: 6006
      nodePort: 30060
    - name: grpc
      port: 4317
      targetPort: 4317
