apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - onepassword-item.yaml
  - openrouter-onepassword-item.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: litellm-config
    files:
      - config.yaml=litellm-config.yaml
