model_list:
  - model_name: step-3.5-flash
    litellm_params:
      model: openrouter/stepfun/step-3.5-flash
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: step-3.5-flash:free
    litellm_params:
      model: openrouter/stepfun/step-3.5-flash:free
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: claude-opus-4-6
    litellm_params:
      model: openrouter/anthropic/claude-opus-4-6
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: claude-sonnet-4
    litellm_params:
      model: openrouter/anthropic/claude-sonnet-4
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: gemini-3-pro
    litellm_params:
      model: openrouter/google/gemini-3-pro
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: glm-5
    litellm_params:
      model: openrouter/z-ai/glm-5
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: deepseek-v3.2
    litellm_params:
      model: openrouter/deepseek/deepseek-v3.2
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: spark/step-3.5-flash
    litellm_params:
      model: openai/Step-3.5-Flash-NVFP4
      api_base: http://192.168.1.249:8000
      api_key: "fake"

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
  callbacks: ["arize_phoenix"]
  cache: true
  cache_params:
    type: redis
    host: redis-service
    port: 6379
    password: os.environ/REDIS_PASSWORD
  database_url: os.environ/DATABASE_URL
